version: '3'
services:
  frontend:
    build:
      context: ./frontend/web
    ports:
      - "5173:5173"
    networks:
      - app-commonCash

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-commonCash

networks:
  app-commonCash: