
version: '3'

services:

  frontend:
    build:
      context: ./Frontend/web
    ports:
      - "5173:5173"
    networks:
      - commonCash

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - commonCash

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - commonCash


volumes:
  mongodb_data:      

networks:
  commonCash:

